service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java11

package:
  artifact: build/distributions/s3-proxy-shadow.zip

functions:
  s3-proxy:
    handler: com.bcchapman.Handler
    events:
      - http:
          path: createFile
          method: post