/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.bcchapman

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2ProxyRequestEvent

class Handler : RequestHandler<APIGatewayV2ProxyRequestEvent, ProxyResponse> {
    companion object {
    }

    override fun handleRequest(input: APIGatewayV2ProxyRequestEvent?, context: Context?): ProxyResponse {

        println("Beginning proxy of message")
        println("Completed proxy of message")

        return ProxyResponse("test-bucket", "test-key", 200)
    }

}